[features]
seeds = false
skip-lint = false
[programs.localnet]
emerald = "CpTEQuYuqgx3fkbtVfLgkyem5GFWC2QCfo36mgYXnTgu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
#cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"

# Metaplex
[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./token_metadata.so"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 5000000 tests/staking-pnft.ts"
init = "yarn run ts-node scripts/init.ts"
community = "yarn run ts-node scripts/community.ts"
collection = "yarn run ts-node scripts/collection.ts"
policy = "yarn run ts-node scripts/policy.ts"
userCommunity = "yarn run ts-node scripts/userCommunity.ts"