[features]
seeds = false
skip-lint = false
[programs.localnet]
emerald = "Ezsukb1BcrnYDw2wAe4Ryy45pAmHcB5ZNVXpZXg7Wsba"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
#cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 5000000 tests/**/*.ts"
init = "yarn run ts-node scripts/init.ts"
community = "yarn run ts-node scripts/community.ts"
collection = "yarn run ts-node scripts/collection.ts"
policy = "yarn run ts-node scripts/policy.ts"
userCommunity = "yarn run ts-node scripts/userCommunity.ts"